### ISSUE TITLE
Traefik example: Real ip not working

### ISSUE THREAD

**Issue by fpauser** [williampsena/podman-recipes#1]
The smoothed out gfx shows the same podman network ip for real-, remote- and traefik container: 10.89.0.25:
![grafik](https://github.com/user-attachments/assets/2411035b-cf7f-481e-a199-cf7f6250ac34)

How to configure the network to get the _real_ remote ip from outside the container, e.g. to be able to block malicious requests with fail2ban?

**Comment by williampsena** [comment]
Welcome ✋😃, depends. In production applications, it is typical to use a load balancer before Traefik or a DNS provider such as Clodflare. So you must ensure that the preceding procedures set the correct client IP address. AWS and Cloudflare use a header called X-Forwarded-For.
